services:
  db:
    image: mariadb:11
    container_name: news_db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-rootpass}
      - MARIADB_DATABASE=${MARIADB_DATABASE:-newsdb}
      - MARIADB_USER=${MARIADB_USER:-user}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: news_backend
    environment:
      - DATABASE_URL=mysql+pymysql://${MARIADB_USER:-user}:${MARIADB_PASSWORD:-password}@db:3306/${MARIADB_DATABASE:-newsdb}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-please-change-me}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-news_events}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=${VITE_API_BASE:-http://localhost:8000}
    container_name: news_web
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
