services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: news_backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-please-change-me}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-news_events}
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  default:
    name: news_net
    external: true
