name: Deploy Web to Firebase Hosting

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/web/**'
      - 'firebase.json'
      - '.github/workflows/firebase-hosting.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install deps (web)
        run: npm ci
        working-directory: apps/web

      - name: Build (web)
        run: npm run build
        working-directory: apps/web
        env:
          VITE_API_BASE: ${{ vars.VITE_API_BASE }}
          VITE_CLIENT_VERSION: ${{ vars.VITE_CLIENT_VERSION }}

      - name: Deploy to Firebase Hosting (live)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '${{ vars.FIREBASE_PROJECT_ID }}'
          channelId: live
        # Notes:
        # - Set repository secret FIREBASE_SERVICE_ACCOUNT to a Service Account JSON
        #   with the "Firebase Hosting Admin" role for your project.
        # - Set repository variable FIREBASE_PROJECT_ID to your Firebase project id.
